language: python
python:
    - "2.7"
sudo: required
dist: trusty
cache:
    directories:
        - "~/.platformio"
env:
    - PLATFORMIO_CI_SRC=examples/Console/Console/
matrix:
    allow_failures:
        - env: PLATFORMIO_CI_SRC=examples/Console/Console/
install:
    - pip install -U platformio
    - platformio lib -g install TimerOne 872
    # Tmp fix for Microchip gcc-pic32
    - sudo apt-get install lib32z1 lib32ncurses5 lib32bz2-1.0
script:
    - platformio ci --lib="." --project-conf "$PLATFORMIO_CI_SRC"/../platformio.ini
